# Generated by Django 3.1.8 on 2021-04-28 19:06

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCampaignForm',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable the Active Campaign integration of this form', verbose_name='Enabled')),
                ('selected_list', models.CharField(blank=True, help_text='Select the Active Campaign list where the new subscribers will be a member of after submission', max_length=255, verbose_name='List')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ActiveCampaignSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable the Active Campaign integration', verbose_name='Enabled')),
                ('api_url', models.URLField(blank=True, help_text='The Active Campaign API URL', verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, help_text='The Active Campain API key', max_length=255, verbose_name='API key')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Active Campaign settings',
                'verbose_name_plural': 'Active Campaign settings',
            },
        ),
        migrations.CreateModel(
            name='ActiveCampaignFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('mapping', models.CharField(blank=True, choices=[('email', 'email'), ('firstName', 'firstName'), ('lastName', 'lastName'), ('phone', 'phone')], help_text='Select the mapped Active Campaign field', max_length=255, verbose_name='Map field to')),
                ('form', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='wagtail_active_campaign.activecampaignform')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='activecampaignformfield',
            constraint=models.UniqueConstraint(fields=('form', 'mapping'), name='A mapping field can only be used once for each form'),
        ),
    ]
