# Generated by Django 3.1.8 on 2021-04-29 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCampaignSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable the Active Campaign integration', verbose_name='Enabled')),
                ('api_url', models.URLField(blank=True, help_text='The Active Campaign API URL', verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, help_text='The Active Campain API key', max_length=255, verbose_name='API key')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Active Campaign settings',
                'verbose_name_plural': 'Active Campaign settings',
            },
        ),
    ]
