# Generated by Django 3.1.8 on 2021-05-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriptionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('active-campaign', 'Active Campaign')], default='active-campaign', max_length=255, verbose_name='Provider')),
                ('enabled', models.BooleanField(default=False, help_text='Enable or disable this integration', verbose_name='Enabled')),
                ('api_url', models.URLField(blank=True, help_text='The API URL', verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, help_text='The API key', max_length=255, verbose_name='API key')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Email Subscription Settings',
                'verbose_name_plural': 'Email Subscription Settings',
            },
        ),
    ]
